.TH IMV 1 "" "" "multimedia"
.SH NAME
imv \- image viewer
.SH SYNOPSIS
.nf
\fBimv\fP [OPTIONS] [IMAGES]
.fi
.sp
.SH DESCRIPTION
.sp
\fBimv\fP is a X11/Wayland image viewer aimed at users of tiling window managers.
It supports a wide variety of image file formats, including animated gif files.
.SH OPTIONS
.TP
.B -i
Read paths from stdin. One path per line.
.TP
.B -r
Recursively search input paths for files.
.TP
.B -f
Start in full screen mode
.TP
.B -a
Default to showing images at actual size.
.TP
.B -h
Print help.
.SH CONTROLs
.sp
imv can be controlled using the mouse or keyboard.
.TP
.B Drag + Left Mouse Button
Pan.
.TP
.B MouseWheel
Zoom in and out.
.TP
.B q
Quit.
.TP
.B LEFT and [
Change to previous image.
.TP
.B RIGHT and ]
Change to next image.
.TP
.B i and \&+ and UP
Zoom in.
.TP
.B o and \- and DOWN
Zoom out.
.TP
.B r
Reset view.
.TP
.B a
View image at actual size.
.TP
.B c
Center image in window.
.TP
.B h
Pan left.
.TP
.B j
Pan down.
.TP
.B k
Pan up.
.TP
.B l
Pan right.
.TP
.B x
Close current image.
.TP
.B f
Toggle fullscreen.
.TP
.B SPACE
Pause gif playback (pressing again unpauses).
.TP
.B \&.
Step forward one frame (when playing gifs).
.TP
.B p
Print current image path to stdout
.SH LEGAL
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
.LP
This software uses the FreeImage open source image library.
See http://freeimage.sourceforge.net for details.
FreeImage is used under the GNU GPLv2.
.SH AUTHOR
Harry Jeffery
